### ISSUE TITLE
Support for HTTPS tracing protocol

### ISSUE THREAD

**Issue by danielloader** [inception-health/otel-export-trace-action#194]
It looks from glancing at the [source](https://github.com/inception-health/otel-export-trace-action/blob/main/src/tracing/trace.ts#L8C76-L8C76) this action only supports gRPC for the OTEL traces, can I confirm this is correct?

Looks that you'd need to import/use https://www.npmjs.com/package/@opentelemetry/exporter-trace-otlp-proto conditionally based on the environment variable for the protocol, or pickup and guess from the endpoint protocol prefix in the URI.

Was trying to use the action with grafana cloud but they haven't got gRPC support yet for ingesting OTEL tracing spans and as expected if the above assumption is true then it's an expected failure.

``` yaml
      - name: Export Workflow Trace
        uses: inception-health/otel-export-trace-action@latest
        env: 
          OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
        with:
          otlpEndpoint: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp
          otlpHeaders: "Authorization=Basic ${{ secrets.OLTP_ACTIONS_TRACES_HEADER }}"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
```

Source: https://grafana.com/docs/grafana-cloud/send-data/otlp/send-data-otlp/#push-directly-from-applications-using-the-opentelemetry-sdks

https://opentelemetry.io/docs/concepts/sdk-configuration/otlp-exporter-configuration/#otel_exporter_otlp_traces_protocol
