### ISSUE TITLE
Very long root spans

### ISSUE THREAD

**Issue by bixu** [inception-health/otel-export-trace-action#2]
We have seen issues where, when triggering a matrix build workflow, the root span for the trace in Honeycomb.io is taking many millions of milliseconds.

Example screenshot is attached, as well as our final Actions Job config, using this action:

```
  send-build-traces:
    name: Send Build Traces to Honeycomb
    runs-on: ubuntu-latest
    needs: [publish-code-coverage]
    steps:
      - name: Export Workflow Trace
        uses: inception-health/otel-export-trace-action@f22eb04b36dce4f973201d5f0afcca5decc42e3a
        with:
          otlpEndpoint: grpc://api.honeycomb.io:443/
          otlpHeaders: x-honeycomb-team=${{ secrets.API_KEY }},x-honeycomb-dataset=XXXXX
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

Example trace: 
<img width="1030" alt="very long builds" src="https://user-images.githubusercontent.com/339799/150165001-4a65656d-abcd-4cb3-b852-ab5e29c89bbb.png">

CC @yonatankarp-sumup
